"""
VillagesML database schema mapping.

The public API uses logical table/column names. Each database key maps those
logical names to the physical SQLite tables and columns used by that dataset.
"""

DEFAULT_DATABASE_KEY = "village"


VILLAGES_DATABASES = {
    "village": {
        "path_key": "village",
        "tables": {
            "villages": {
                "name": "广东省自然村_预处理",
                "logical_name": "广东省自然村_预处理",
                "columns": {
                    "rowid": "ROWID",
                    "village_id": "village_id",
                    "name": "自然村_去前缀",
                    "raw_name": "自然村",
                    "committee": "村委会",
                    "city": "市级",
                    "county": "区县级",
                    "township": "乡镇级",
                    "longitude": "longitude",
                    "latitude": "latitude",
                },
            },
            "villages_raw": {
                "name": "广东省自然村",
                "logical_name": "广东省自然村",
                "columns": {
                    "name": "自然村",
                    "committee": "村委会",
                    "city": "市级",
                    "county": "区县级",
                    "township": "乡镇级",
                    "longitude": "longitude",
                    "latitude": "latitude",
                },
            },
            "active_run_ids": {
                "name": "active_run_ids",
                "columns": {
                    "analysis_type": "analysis_type",
                    "run_id": "run_id",
                    "table_name": "table_name",
                    "updated_at": "updated_at",
                    "updated_by": "updated_by",
                    "notes": "notes",
                },
            },
            "analysis_runs": {
                "name": "analysis_runs",
                "columns": {
                    "run_id": "run_id",
                    "created_at": "created_at",
                    "status": "status",
                    "total_villages": "total_villages",
                    "total_chars": "total_chars",
                },
            },
            "embedding_runs": {
                "name": "embedding_runs",
                "columns": {
                    "run_id": "run_id",
                    "created_at": "created_at",
                    "vector_size": "vector_size",
                    "window_size": "window_size",
                    "min_count": "min_count",
                },
            },
            "char_frequency_global": {
                "name": "char_frequency_global",
                "columns": {
                    "char": "char",
                    "frequency": "frequency",
                    "village_count": "village_count",
                    "rank": "rank",
                },
            },
            "char_regional_analysis": {
                "name": "char_regional_analysis",
                "columns": {
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "township": "township",
                    "char": "char",
                    "frequency": "frequency",
                    "village_count": "village_count",
                    "rank_within_region": "rank_within_region",
                    "lift": "lift",
                    "log_odds": "log_odds",
                    "z_score": "z_score",
                },
            },
            "tendency_significance": {
                "name": "tendency_significance",
                "run_id": {"analysis_type": "char_significance", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "char": "char",
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "township": "township",
                    "chi_square_statistic": "chi_square_statistic",
                    "p_value": "p_value",
                    "is_significant": "is_significant",
                    "effect_size": "effect_size",
                },
            },
            "char_embeddings": {
                "name": "char_embeddings",
                "run_id": {"analysis_type": "char_embeddings", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "char": "char",
                    "embedding_vector": "embedding_vector",
                    "char_frequency": "char_frequency",
                },
            },
            "char_similarity": {
                "name": "char_similarity",
                "run_id": {"analysis_type": "char_embeddings", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "char1": "char1",
                    "char2": "char2",
                    "cosine_similarity": "cosine_similarity",
                },
            },
            "village_features": {
                "name": "village_features",
                "run_id": {"analysis_type": "village_features", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "village_id": "village_id",
                    "village_name": "village_name",
                    "village_committee": "village_committee",
                    "city": "city",
                    "county": "county",
                    "town": "town",
                    "semantic_tags": "semantic_tags",
                    "suffix": "suffix",
                    "suffix_1": "suffix_1",
                    "suffix_2": "suffix_2",
                    "suffix_3": "suffix_3",
                    "prefix_1": "prefix_1",
                    "prefix_2": "prefix_2",
                    "prefix_3": "prefix_3",
                    "name_length": "name_length",
                    "cluster_id": "cluster_id",
                    "sem_agriculture": "sem_agriculture",
                    "sem_clan": "sem_clan",
                    "sem_culture": "sem_culture",
                    "sem_modifier": "sem_modifier",
                    "sem_settlement": "sem_settlement",
                    "sem_spatial": "sem_spatial",
                    "sem_terrain": "sem_terrain",
                    "sem_vegetation": "sem_vegetation",
                    "sem_water": "sem_water",
                },
            },
            "village_spatial_features": {
                "name": "village_spatial_features",
                "columns": {
                    "village_id": "village_id",
                    "village_name": "village_name",
                    "city": "city",
                    "county": "county",
                    "town": "town",
                    "longitude": "longitude",
                    "latitude": "latitude",
                    "nn_distance_1": "nn_distance_1",
                    "nn_distance_5": "nn_distance_5",
                    "nn_distance_10": "nn_distance_10",
                    "local_density_1km": "local_density_1km",
                    "local_density_5km": "local_density_5km",
                    "local_density_10km": "local_density_10km",
                    "isolation_score": "isolation_score",
                    "is_isolated": "is_isolated",
                    "knn_mean_distance": "knn_mean_distance",
                    "local_density": "local_density",
                },
            },
            "village_cluster_assignments": {
                "name": "village_cluster_assignments",
                "run_id": {"analysis_type": "spatial_clusters", "column": "run_id"},
                "columns": {
                    "village_id": "village_id",
                    "run_id": "run_id",
                    "cluster_id": "cluster_id",
                },
            },
            "village_ngrams": {
                "name": "village_ngrams",
                "columns": {
                    "committee": "村委会",
                    "name": "自然村",
                    "bigrams": "bigrams",
                    "trigrams": "trigrams",
                    "prefix_bigram": "prefix_bigram",
                    "suffix_bigram": "suffix_bigram",
                },
            },
            "village_semantic_structure": {
                "name": "village_semantic_structure",
                "columns": {
                    "village_id": "village_id",
                    "committee": "村委会",
                    "name": "自然村",
                    "semantic_sequence": "semantic_sequence",
                    "sequence_length": "sequence_length",
                    "has_modifier": "has_modifier",
                    "has_head": "has_head",
                    "has_settlement": "has_settlement",
                },
            },
            "semantic_indices": {
                "name": "semantic_indices",
                "run_id": {"analysis_type": "semantic_indices", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "township": "township",
                    "category": "category",
                    "raw_intensity": "raw_intensity",
                    "normalized_index": "normalized_index",
                    "rank_within_province": "rank_within_province",
                    "vector_json": "vector_json",
                    "village_count": "village_count",
                },
            },
            "semantic_indices_detailed": {
                "name": "semantic_indices_detailed",
                "run_id": {"analysis_type": "semantic_indices", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "township": "township",
                    "category": "category",
                    "raw_intensity": "raw_intensity",
                    "normalized_index": "normalized_index",
                    "z_score": "z_score",
                    "rank_within_province": "rank_within_province",
                    "village_count": "village_count",
                },
            },
            "semantic_vtf_global": {
                "name": "semantic_vtf_global",
                "columns": {
                    "run_id": "run_id",
                    "category": "category",
                    "vtf_count": "vtf_count",
                    "village_count": "village_count",
                    "total_villages": "total_villages",
                    "frequency": "frequency",
                    "vtf": "vtf",
                    "char_count": "char_count",
                    "rank": "rank",
                },
            },
            "semantic_regional_analysis": {
                "name": "semantic_regional_analysis",
                "columns": {
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "township": "township",
                    "category": "category",
                    "frequency": "frequency",
                    "lift": "lift",
                    "z_score": "z_score",
                },
            },
            "semantic_labels": {
                "name": "semantic_labels",
                "columns": {
                    "char": "char",
                    "semantic_category": "semantic_category",
                    "confidence": "confidence",
                    "llm_explanation": "llm_explanation",
                },
            },
            "semantic_subcategory_vtf_global": {
                "name": "semantic_subcategory_vtf_global",
                "columns": {
                    "subcategory": "subcategory",
                    "parent_category": "parent_category",
                    "char_count": "char_count",
                    "village_count": "village_count",
                    "vtf": "vtf",
                    "percentage": "percentage",
                },
            },
            "semantic_subcategory_vtf_regional": {
                "name": "semantic_subcategory_vtf_regional",
                "columns": {
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "township": "township",
                    "subcategory": "subcategory",
                    "parent_category": "parent_category",
                    "char_count": "char_count",
                    "village_count": "village_count",
                    "vtf": "vtf",
                    "percentage": "percentage",
                    "tendency": "tendency",
                },
                "column_value_maps": {
                },
            },
            "semantic_bigrams": {
                "name": "semantic_bigrams",
                "columns": {
                    "category1": "category1",
                    "category2": "category2",
                    "frequency": "frequency",
                    "percentage": "percentage",
                    "pmi": "pmi",
                },
            },
            "semantic_bigrams_detailed": {
                "name": "semantic_bigrams_detailed",
                "columns": {
                    "category1": "category1",
                    "category2": "category2",
                    "frequency": "frequency",
                    "percentage": "percentage",
                    "pmi": "pmi",
                },
            },
            "semantic_trigrams": {
                "name": "semantic_trigrams",
                "columns": {
                    "category1": "category1",
                    "category2": "category2",
                    "category3": "category3",
                    "frequency": "frequency",
                    "percentage": "percentage",
                },
            },
            "semantic_trigrams_detailed": {
                "name": "semantic_trigrams_detailed",
                "columns": {
                    "category1": "category1",
                    "category2": "category2",
                    "category3": "category3",
                    "frequency": "frequency",
                    "percentage": "percentage",
                },
            },
            "semantic_pmi": {
                "name": "semantic_pmi",
                "columns": {
                    "category1": "category1",
                    "category2": "category2",
                    "pmi": "pmi",
                    "frequency": "frequency",
                    "is_positive": "is_positive",
                },
            },
            "semantic_pmi_detailed": {
                "name": "semantic_pmi_detailed",
                "columns": {
                    "category1": "category1",
                    "category2": "category2",
                    "pmi": "pmi",
                    "frequency": "frequency",
                    "is_positive": "is_positive",
                },
            },
            "semantic_composition_patterns": {
                "name": "semantic_composition_patterns",
                "columns": {
                    "pattern": "pattern",
                    "pattern_type": "pattern_type",
                    "modifier": "modifier",
                    "head": "head",
                    "frequency": "frequency",
                    "percentage": "percentage",
                    "description": "description",
                },
            },
            "semantic_composition_patterns_detailed": {
                "name": "semantic_composition_patterns_detailed",
                "columns": {
                    "pattern": "pattern",
                    "pattern_type": "pattern_type",
                    "modifier": "modifier",
                    "head": "head",
                    "frequency": "frequency",
                    "percentage": "percentage",
                    "description": "description",
                },
            },
            "spatial_hotspots": {
                "name": "spatial_hotspots",
                "run_id": {"analysis_type": "spatial_hotspots", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "hotspot_id": "hotspot_id",
                    "center_lon": "center_lon",
                    "center_lat": "center_lat",
                    "density_score": "density_score",
                    "village_count": "village_count",
                    "radius_km": "radius_km",
                },
            },
            "spatial_clusters": {
                "name": "spatial_clusters",
                "run_id": {"analysis_type": "spatial_clusters", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "cluster_id": "cluster_id",
                    "cluster_size": "cluster_size",
                    "centroid_lon": "centroid_lon",
                    "centroid_lat": "centroid_lat",
                    "avg_distance_km": "avg_distance_km",
                    "dominant_city": "dominant_city",
                    "dominant_county": "dominant_county",
                },
            },
            "spatial_tendency_integration": {
                "name": "spatial_tendency_integration",
                "run_id": {"analysis_type": "spatial_integration", "column": "run_id"},
                "columns": {
                    "id": "id",
                    "run_id": "run_id",
                    "tendency_run_id": "tendency_run_id",
                    "spatial_run_id": "spatial_run_id",
                    "character": "character",
                    "character_category": "character_category",
                    "cluster_id": "cluster_id",
                    "cluster_tendency_mean": "cluster_tendency_mean",
                    "cluster_tendency_std": "cluster_tendency_std",
                    "global_tendency_mean": "global_tendency_mean",
                    "tendency_deviation": "tendency_deviation",
                    "cluster_size": "cluster_size",
                    "n_villages_with_char": "n_villages_with_char",
                    "centroid_lon": "centroid_lon",
                    "centroid_lat": "centroid_lat",
                    "avg_distance_km": "avg_distance_km",
                    "spatial_coherence": "spatial_coherence",
                    "spatial_specificity": "spatial_specificity",
                    "dominant_city": "dominant_city",
                    "dominant_county": "dominant_county",
                    "is_significant": "is_significant",
                    "p_value": "p_value",
                    "u_statistic": "u_statistic",
                },
            },
            "cluster_assignments": {
                "name": "cluster_assignments",
                "run_id": {"analysis_type": "clustering_county", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "algorithm": "algorithm",
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "cluster_id": "cluster_id",
                    "distance_to_centroid": "distance_to_centroid",
                },
            },
            "cluster_profiles": {
                "name": "cluster_profiles",
                "run_id": {"analysis_type": "clustering_county", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "algorithm": "algorithm",
                    "cluster_id": "cluster_id",
                    "cluster_size": "cluster_size",
                    "top_features_json": "top_features_json",
                    "top_semantic_categories_json": "top_semantic_categories_json",
                    "top_suffixes_json": "top_suffixes_json",
                },
            },
            "clustering_metrics": {
                "name": "clustering_metrics",
                "run_id": {"analysis_type": "clustering_county", "column": "run_id"},
                "columns": {
                    "run_id": "run_id",
                    "algorithm": "algorithm",
                    "k": "k",
                    "silhouette_score": "silhouette_score",
                    "davies_bouldin_index": "davies_bouldin_index",
                    "calinski_harabasz_score": "calinski_harabasz_score",
                },
            },
            "ngram_frequency": {
                "name": "ngram_frequency",
                "columns": {
                    "ngram": "ngram",
                    "position": "position",
                    "frequency": "frequency",
                    "percentage": "percentage",
                    "n": "n",
                },
            },
            "regional_ngram_frequency": {
                "name": "regional_ngram_frequency",
                "columns": {
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "township": "township",
                    "ngram": "ngram",
                    "frequency": "frequency",
                    "percentage": "percentage",
                    "n": "n",
                },
            },
            "pattern_frequency_global": {
                "name": "pattern_frequency_global",
                "columns": {
                    "pattern": "pattern",
                    "pattern_type": "pattern_type",
                    "frequency": "frequency",
                    "village_count": "village_count",
                    "rank": "rank",
                },
            },
            "pattern_regional_analysis": {
                "name": "pattern_regional_analysis",
                "columns": {
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "township": "township",
                    "pattern": "pattern",
                    "pattern_type": "pattern_type",
                    "frequency": "frequency",
                    "global_frequency": "global_frequency",
                    "rank_within_region": "rank_within_region",
                    "lift": "lift",
                },
            },
            "structural_patterns": {
                "name": "structural_patterns",
                "columns": {
                    "pattern": "pattern",
                    "pattern_type": "pattern_type",
                    "n": "n",
                    "position": "position",
                    "frequency": "frequency",
                    "example": "example",
                    "description": "description",
                },
            },
            "ngram_tendency": {
                "name": "ngram_tendency",
                "columns": {
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "township": "township",
                    "ngram": "ngram",
                    "n": "n",
                    "position": "position",
                    "lift": "lift",
                    "log_odds": "log_odds",
                    "z_score": "z_score",
                    "regional_count": "regional_count",
                    "regional_total": "regional_total",
                    "regional_total_raw": "regional_total_raw",
                    "global_count": "global_count",
                    "global_total": "global_total",
                },
            },
            "regional_centroids": {
                "name": "regional_centroids",
                "columns": {
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "centroid_lon": "centroid_lon",
                    "centroid_lat": "centroid_lat",
                },
            },
            "ngram_significance": {
                "name": "ngram_significance",
                "columns": {
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "township": "township",
                    "ngram": "ngram",
                    "n": "n",
                    "position": "position",
                    "chi2": "chi2",
                    "p_value": "p_value",
                    "is_significant": "is_significant",
                    "cramers_v": "cramers_v",
                    "total_before_filter": "total_before_filter",
                },
            },
            "region_spatial_aggregates": {
                "name": "region_spatial_aggregates",
                "columns": {
                    "region_level": "region_level",
                    "region_name": "region_name",
                    "city": "city",
                    "county": "county",
                    "town": "town",
                    "total_villages": "total_villages",
                    "avg_lon": "avg_lon",
                    "avg_lat": "avg_lat",
                    "density": "density",
                    "area_km2": "area_km2",
                    "spatial_spread": "spatial_spread",
                    "nearest_neighbor_avg": "nearest_neighbor_avg",
                    "avg_local_density": "avg_local_density",
                    "avg_nn_distance": "avg_nn_distance",
                    "avg_isolation_score": "avg_isolation_score",
                    "spatial_dispersion": "spatial_dispersion",
                    "n_isolated_villages": "n_isolated_villages",
                    "n_spatial_clusters": "n_spatial_clusters",
                },
            },
            "region_vectors": {
                "name": "region_vectors",
                "columns": {
                    "region_id": "region_id",
                    "region_name": "region_name",
                    "region_level": "region_level",
                    "N_villages": "N_villages",
                    "created_at": "created_at",
                },
            },
            "region_similarity": {
                "name": "region_similarity",
                "columns": {
                    "region1": "region1",
                    "region2": "region2",
                    "region_level": "region_level",
                    "cosine_similarity": "cosine_similarity",
                    "jaccard_similarity": "jaccard_similarity",
                    "euclidean_distance": "euclidean_distance",
                    "common_high_tendency_chars": "common_high_tendency_chars",
                    "distinctive_chars_r1": "distinctive_chars_r1",
                    "distinctive_chars_r2": "distinctive_chars_r2",
                    "feature_dimension": "feature_dimension",
                },
            },
            "sqlite_master": {
                "name": "sqlite_master",
                "columns": {
                    "name": "name",
                    "table_name": "tbl_name",
                    "type": "type",
                },
            },
            "sqlite_stat1": {
                "name": "sqlite_stat1",
                "columns": {
                    "table_name": "tbl",
                    "stat": "stat",
                },
            },
            "dbstat": {
                "name": "dbstat",
                "columns": {
                    "name": "name",
                    "page_size": "pgsize",
                },
            },
            "city_aggregates": {
                "name": "city_aggregates",
                "columns": {
                    "city": "city",
                    "total_villages": "total_villages",
                },
            },
            "county_aggregates": {
                "name": "county_aggregates",
                "columns": {
                    "city": "city",
                    "county": "county",
                    "total_villages": "total_villages",
                },
            },
            "town_aggregates": {
                "name": "town_aggregates",
                "columns": {
                    "city": "city",
                    "county": "county",
                    "town": "town",
                    "total_villages": "total_villages",
                },
            },
        },
        "table_lists": {
            "database_statistics": [
                "regional_ngram_frequency",
                "ngram_tendency",
                "ngram_significance",
                "pattern_regional_analysis",
                "char_regional_analysis",
                "semantic_regional_analysis",
            ],
        },
        "table_variants": {
            "semantic_bigrams_by_detail": {
                False: "semantic_bigrams",
                True: "semantic_bigrams_detailed",
            },
            "semantic_trigrams_by_detail": {
                False: "semantic_trigrams",
                True: "semantic_trigrams_detailed",
            },
            "semantic_pmi_by_detail": {
                False: "semantic_pmi",
                True: "semantic_pmi_detailed",
            },
            "semantic_composition_patterns_by_detail": {
                False: "semantic_composition_patterns",
                True: "semantic_composition_patterns_detailed",
            },
            "semantic_indices_by_detail": {
                False: "semantic_indices",
                True: "semantic_indices_detailed",
            },
        },
        "region_levels": {
            "compute_aggregate_features": {
                "city": {
                    "region_col": "city",
                    "group_cols": ["city"],
                    "filter_col": "city",
                    "agg_table": "city_aggregates",
                },
                "county": {
                    "region_col": "county",
                    "group_cols": ["city", "county"],
                    "filter_col": "city",
                    "agg_table": "county_aggregates",
                },
                "township": {
                    "region_col": "town",
                    "group_cols": ["city", "county", "town"],
                    "filter_col": "county",
                    "agg_table": "town_aggregates",
                },
            },
            "compute_feature_aggregation": {
                "city": {"group_cols": ["city"]},
                "county": {"group_cols": ["city", "county"]},
                "township": {"group_cols": ["city", "county", "town"]},
            },
        },
    }
}
